import Head from 'next/head'
import Catalog from "../../app/Catalog/Catalog";


export default function CatalogPage() {
	return (
		<>
			<Head>
				<title>Catalog</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Catalog/>
		</>
	)
}
