import Head from 'next/head'
import General from "../../app/Home/Home";


export default function Home() {
  return (
    <>
      <Head>
        <title>Shopic by Anton</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <General/>
    </>
  )
}
